name: clqmtch JAR release
on:
  workflow_dispatch:
  release:
    types: [created]
  create:
    tags:
      - java-v.*

jobs:
  build_jar:
    name: build clqmtch JAR
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target_arch: [x64, aarch64]
    steps:
      - name: checkout repo
        id: checkout_repo
        uses: actions/checkout@v4
      - name: setup JDK
        uses: actions/setup-java@v4
        id: jdk_setup
        with:
          distribution: 'adopt'
          java-version: '8'
      - name: build JAR
        run: bash ./.github/scripts/build-jar.sh
      - name: upload release assets
        id: upload_assets
        uses: svenstaro/upload-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION_NUMBER: ${{ env.VERSION_NUMBER }}
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/clqmtch-1.0-SNAPSHOT.jar
          overwrite: true
          asset_name: clqmtch-1.0-${{ matrix.target_arch }}.jar
